export const projects = [
  { name: 'Dora Hacks', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715152899666_dora-hacks.jpeg'},
  { name: 'Magnify Cash', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715182705214_magnify-cash.png'},
  { name: 'Degan', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715244757190_degen.jpeg'},
  { name: 'Baked Beans', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715317662641_baked-beans-reloaded.png'},
  { name: 'Karak', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715035432552_karak.jpeg'},
  { name: 'Eoracle', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715035759521_eoracle.jpeg'},
  { name: 'Umbra', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1714462938858_umbra.jpeg'},
  { name: 'Tuyo', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715262323236_tuyo.jpeg'},
  { name: 'Bubblewars.io', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1713890246706_bubblewars-io.jpeg'},
  { name: 'Jam', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715229620621_jam.png'},
  { name: 'HERE Wallet', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1713717878607_here-wallet.png'},
  { name: 'Degan', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715244757190_degen.jpeg'},
  { name: 'Magnify Cash', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1715182705214_magnify-cash.png'},
  { name: 'Bubblewars.io', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1713890246706_bubblewars-io.jpeg'},
  { name: 'Umbra', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, nisl quis tincidunt iaculis, augue tortor aliquet justo, vel scelerisque elit ipsum eget nulla', address: '0x1786.....A583', upvotes: 29, logo: 'https://images.thedapplist.com/prod/uploads/projects/image_1714462938858_umbra.jpeg'},

]